# Generated by Django 5.1.6 on 2025-03-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_product',
            name='product_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
