# Generated by Django 5.1.6 on 2025-03-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('loc_add', models.CharField(max_length=100)),
                ('loc_link', models.URLField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('insta_name', models.CharField(max_length=30)),
                ('insta_link', models.URLField(max_length=300)),
            ],
        ),
    ]
