# Generated by Django 5.1.6 on 2025-03-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='insta_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='insta_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
