# Generated by Django 5.1.6 on 2025-03-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_store_insta_link_alter_store_insta_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='number',
            field=models.CharField(max_length=5),
        ),
    ]
